### ISSUE TITLE
Header error with Docker container usage

### ISSUE THREAD

**Issue by adamculp** [zendframework/zend-diactoros#350]
- [X] I was not able to find an [open](https://github.com/zendframework/zend-diactoros/issues?q=is%3Aopen) or [closed](https://github.com/zendframework/zend-diactoros/issues?q=is%3Aclosed) issue matching what I'm seeing.
 - [X] This is not a question. (Questions should be asked on [chat](https://zendframework.slack.com/) ([Signup here](https://zendframework-slack.herokuapp.com/)) or our [forums](https://discourse.zendframework.com/c/questions/expressive).)

Provide a narrative description of what you are trying to accomplish.

### Steps to reproduce the issue

* Perform Expressive skeleton install
* Verify that Expressive resolves in browser using Composer serve command. Works OK. (Apache 2.4.29)
* Close down PHP internal web server. (Ctrl+c)
* Create simple docker-compose.yml file to create web server with Dockerfile using php:7.2-apache.
* Now receive error message from HeaderSecurity.php about invalid header:

### Expected results

Expected to receive typical output from Expressive skeleton application output.

### Actual results

```bash
Zend\Diactoros\Exception\InvalidArgumentException raised in file /var/www/vendor/zendframework/zend-diactoros/src/HeaderSecurity.php line 145: Message: "<address>Apache/2.4.25 (Debian) Server at localhost Port 8080</address>" is not valid header value
```

**Comment by adamculp** [comment]
It is possibly the same. But since I experienced the error in a container, but no errors on a local dev environment. So I added this new ticket.

**Comment by maiorano84** [comment]
Bumping this ticket. Also experiencing a similar problem on a Docker installation.

**Comment by Ocramius** [comment]
@maiorano84 tests required

**Comment by maiorano84** [comment]
@Ocramius I've provided a minimal example and the steps to reproduce here:

https://github.com/maiorano84/zend-diactoros-bug-env

If you're using PHPStorm, you should be able to wire up XDebug with the provided configuration and set up a breakpoint on `index.php` to see what I'm talking about.

**Comment by xtreamwayz** [comment]
There are some more issues here. I just encountered some issues with docker containers.

- It has an empty `$_SERVER['argv']` array.
- It has `$_SERVER['affinity:container']` which is marked as invalid and throws an exception.

It took me a while to trace this back to zend-diactoros because the zend-expressive error handler did not kick at the point.

**Wouldn't it be better to filter out invalid keys and values instead of throwing exceptions?**

Right now I created a hack in `index.php`:
```php
    unset($_SERVER['affinity:container']);
    foreach ($_SERVER as $key => $value) {
        if (is_array($value) && empty($value)) {
            unset ($_SERVER[$key]);
        }
    }
```

**Comment by maiorano84** [comment]
@xtreamwayz The `affinity:container` index doesn't appear to be a Docker standard. Can you put together a minimal environment of your own so that this can be verified? See my example above for details.

**Comment by xtreamwayz** [comment]
@maiorano84 This is my docker-compose.yml:

```yaml
version: "3"
services:

  web:
    image: xtreamwayz/nginx
    container_name: web
    ports:
      - "80:80"
    volumes:
      - ./public:/app/public

  php:
    image: xtreamwayz/php:7.1-fpm
    container_name: php
    volumes:
      - .:/app
      - /app/.git
      - /app/.idea
      - /app/data/mysql
      - /app/node_modules

  db:
    image: xtreamwayz/mysql
    container_name: db
    ports:
      - "3306:3306"
    volumes:
      - ./res/mysql-initdb:/docker-entrypoint-initdb.d:ro
      - ./data/mysql:/var/lib/mysql:rw

  redis:
    image: redis:3-alpine
    container_name: redis

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
```

PHP container is based on [php:7.1-fpm-alpine](https://github.com/xtreamwayz/dckr-stack/blob/7f2878ef52b30e59ad952a2085b879daed05b60f/php/php-7.1-fpm#L1), nginx is based on [nginx:stable-alpine](https://github.com/xtreamwayz/dckr-stack/blob/7f2878ef52b30e59ad952a2085b879daed05b60f/nginx/Dockerfile#L1)
